In [3]:
import numpy as np
import torch

a = np.array([2,3.3])
a

array([2. , 3.3])

In [4]:
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [6]:
a = np.ones([2,3])
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
torch.tensor([2.,3.2])


tensor([2.0000, 3.2000])

In [8]:
torch.FloatTensor([2.,3.2])

tensor([2.0000, 3.2000])

In [9]:
torch.tensor([[2.,3.2],[1.,22.3]])


tensor([[ 2.0000,  3.2000],
        [ 1.0000, 22.3000]])

uninitialized 

Torch.empty()

Torch.FloatTensor(d1,d2,d3)

Torch.IntTensor(d1,d2,d3)

In [10]:
#uninitialized
torch.empty(1)

tensor([0.])

In [11]:
torch.Tensor(2,3)

tensor([[1.0800e+37, 1.1883e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [14]:
torch.IntTensor(2,3)

tensor([[2097283744,        848,          0],
        [         0,          0,          0]], dtype=torch.int32)

In [15]:
torch.FloatTensor(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

Set default type

In [16]:
torch.tensor([1.2,3]).type()


'torch.FloatTensor'

In [20]:
torch.set_default_tensor_type(torch.DoubleTensor)

rand/rand_like,randint

In [21]:
torch.rand(2,3)

tensor([[0.3856, 0.4738, 0.0724],
        [0.6440, 0.1687, 0.9201]])

In [23]:
a = torch.rand(3,3)
torch.rand_like(a)

tensor([[0.7163, 0.8446, 0.8506],
        [0.5193, 0.3206, 0.6643],
        [0.8016, 0.2125, 0.0543]])

In [24]:
torch.randint(1,10,[3,3])

tensor([[5, 4, 1],
        [5, 4, 4],
        [8, 8, 5]])

randn

In [25]:
torch.randn(3,3)

tensor([[ 0.5661,  1.5909,  0.8340],
        [-0.0054,  1.5489,  1.5664],
        [ 1.4496, -0.0587, -0.8586]])

In [30]:
import torch

mean = torch.full([10], 0.0)  # Ensure mean is a float tensor
std = torch.arange(1.0, 0.0, -0.1)  # Ensure std is a float tensor
result = torch.normal(mean=mean, std=std)
result

tensor([ 1.9293, -0.8052, -1.3710, -0.5049, -0.5950,  0.5046, -0.4188, -0.3789,
         0.0689,  0.0713])

In [31]:
torch.full([2,3],7)

tensor([[7, 7, 7],
        [7, 7, 7]])

In [32]:
torch.full([],7)

tensor(7)

In [34]:
torch.full([1],7)

tensor([7])

arange\range

In [36]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [38]:
torch.range(0,10)

C:\Users\夜游独行\AppData\Local\Temp\ipykernel_3944\497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

linspace/logspace

In [39]:
torch.linspace(0,10,4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [40]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [41]:
torch.linspace(0,10,11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [42]:
torch.logspace(0,-1,steps=10) # 10^0 to 10^-1

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

In [43]:
torch.logspace(0,1,steps=10)

tensor([ 1.0000,  1.2915,  1.6681,  2.1544,  2.7826,  3.5938,  4.6416,  5.9948,
         7.7426, 10.0000])

Ones/zeors/eye

In [44]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [45]:
torch.zeros(3,3)    

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [46]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [47]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [48]:
a = torch.zeros(3,3)
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

randperm

random.shuffle

In [49]:
torch.randperm(10)

tensor([5, 9, 7, 2, 1, 0, 3, 8, 6, 4])

In [51]:
a = torch.rand(2,3)
b = torch.rand(2,2)
idx = torch.randperm(2) 
# randperm的作用是打乱索引，这样就可以用来打乱数据集
idx

tensor([0, 1])

In [53]:
a[idx]

tensor([[0.3930, 0.5389, 0.0322],
        [0.4642, 0.9727, 0.7663]])

In [54]:
b[idx]

tensor([[0.0040, 0.8398],
        [0.1173, 0.0429]])

In [55]:
a,b

(tensor([[0.3930, 0.5389, 0.0322],
         [0.4642, 0.9727, 0.7663]]),
 tensor([[0.0040, 0.8398],
         [0.1173, 0.0429]]))