Sqeeze/unsqueeze

Transpose/t/permute

Expand/repeat

In [4]:
import torch

a = torch.rand(4,1,28,28)
a.shape

torch.Size([4, 1, 28, 28])

In [6]:
a.view(4,28*28)

tensor([[8.6335e-01, 2.1513e-01, 6.7275e-01,  ..., 4.3619e-04, 2.4974e-02,
         8.4803e-01],
        [2.7660e-01, 7.3089e-01, 7.1456e-01,  ..., 2.1206e-01, 5.3486e-01,
         6.4780e-01],
        [3.0365e-01, 2.2230e-01, 1.1408e-01,  ..., 7.1106e-01, 2.2030e-01,
         5.9890e-01],
        [9.5781e-01, 7.9946e-01, 7.1305e-01,  ..., 6.6892e-01, 3.6820e-01,
         4.4156e-03]])

In [8]:
a.view(4,28*28).shape

torch.Size([4, 784])

In [9]:
a.view(4*28,28).shape

torch.Size([112, 28])

In [10]:
a.view(4*1,28,28).shape

torch.Size([4, 28, 28])

In [13]:
b = a.view(4,784)
b.view(4,28,28,1) #Logic bug

tensor([[[[8.6335e-01],
          [2.1513e-01],
          [6.7275e-01],
          ...,
          [9.9471e-01],
          [5.6424e-01],
          [6.0487e-01]],

         [[1.4513e-01],
          [6.9708e-01],
          [3.5901e-01],
          ...,
          [7.7749e-01],
          [1.3483e-01],
          [6.9550e-01]],

         [[5.9468e-01],
          [2.1338e-01],
          [8.4743e-01],
          ...,
          [9.7982e-01],
          [4.2639e-01],
          [3.6060e-01]],

         ...,

         [[2.6207e-01],
          [9.8198e-01],
          [8.7013e-01],
          ...,
          [3.5850e-02],
          [1.6851e-01],
          [8.7526e-01]],

         [[8.1966e-01],
          [8.4495e-01],
          [2.0692e-01],
          ...,
          [7.8300e-02],
          [8.5157e-01],
          [4.3493e-01]],

         [[7.0008e-01],
          [1.1920e-01],
          [3.5035e-01],
          ...,
          [4.3619e-04],
          [2.4974e-02],
          [8.4803e-01]]],


        [[[2.7660

In [16]:
a.view(4,783)#Flexible but prone to corrupt

RuntimeError: shape '[4, 783]' is invalid for input of size 3136

Squeeze vs unsqueeze

In [17]:
a.shape

torch.Size([4, 1, 28, 28])

In [18]:
a.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [19]:
a.unsqueeze(-1).shape

torch.Size([4, 1, 28, 28, 1])

In [20]:
a.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])

In [21]:
a.unsqueeze(-4).shape

torch.Size([4, 1, 1, 28, 28])

In [22]:
a.unsqueeze(-5).shape

torch.Size([1, 4, 1, 28, 28])

In [23]:
a.unsqueeze(5).shape

IndexError: Dimension out of range (expected to be in range of [-5, 4], but got 5)

In [27]:
a = torch.tensor([1.2,2.3])
print(a.shape)
print(a.unsqueeze(-1).shape)
a.unsqueeze(-1)


torch.Size([2])
torch.Size([2, 1])


tensor([[1.2000],
        [2.3000]])

In [30]:
print(a.unsqueeze(0).shape)
a.unsqueeze(0)

torch.Size([1, 2])


tensor([[1.2000, 2.3000]])

In [33]:
b = torch.rand(32)
print(b.unsqueeze(1).shape)
print(b.unsqueeze(1).unsqueeze(2).shape)
f = torch.rand(4,32,14,14)
b = b.unsqueeze(1).unsqueeze(2).unsqueeze(0)
b.shape

torch.Size([32, 1])
torch.Size([32, 1, 1])


torch.Size([1, 32, 1, 1])

In [34]:
b.shape

torch.Size([1, 32, 1, 1])

In [35]:
b.squeeze().shape

torch.Size([32])

In [36]:
b.squeeze(0).shape

torch.Size([32, 1, 1])

In [37]:
b.squeeze(-1).shape

torch.Size([1, 32, 1])

In [38]:
b.squeeze(1).shape

torch.Size([1, 32, 1, 1])

In [39]:
b.squeeze(-4).shape

torch.Size([32, 1, 1])

Expand/repeat


Expand:broadcasting

Repeat:memory copied

In [41]:
a = torch.rand(4,32,14,14)
b.shape

torch.Size([1, 32, 1, 1])

In [42]:
b.expand(4,32,14,14).shape

torch.Size([4, 32, 14, 14])

In [44]:
b.expand(-1,32,-1,-1).shape # -1 means do not change 这是因为-1是一个特殊的值，表示不改变这个维度的大小

torch.Size([1, 32, 1, 1])

In [47]:
b.expand(-1,32,1,-4).shape

torch.Size([1, 32, 1, -4])

In [48]:
b.shape

torch.Size([1, 32, 1, 1])

In [49]:
b.repeat(4,32,1,1).shape

torch.Size([4, 1024, 1, 1])

In [50]:
b.repeat(4,1,1,1).shape

torch.Size([4, 32, 1, 1])

In [51]:
b.repeat(4,1,14,14).shape

torch.Size([4, 32, 14, 14])

In [53]:
b.t()

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 4D

In [56]:
a = torch.rand(3,4)
print(a.t())
a.t().shape


tensor([[0.3731, 0.0927, 0.9625],
        [0.5375, 0.5342, 0.7383],
        [0.1962, 0.9843, 0.8771],
        [0.9217, 0.2197, 0.6863]])


torch.Size([4, 3])

In [58]:
a = torch.rand(4,3,32,32)
a.transpose(1,3).shape

torch.Size([4, 32, 32, 3])

In [60]:
b = torch.rand(4,3,28,32)

b.transpose(1,3).shape

torch.Size([4, 32, 28, 3])

In [61]:
b.transpose(1,3).transpose(1,2).shape

torch.Size([4, 28, 32, 3])

In [62]:
b.permute(0,2,3,1).shape

torch.Size([4, 28, 32, 3])