indexing

In [2]:
import torch
a = torch.rand(4,3,28,28)
a

tensor([[[[0.9927, 0.3406, 0.0731,  ..., 0.7586, 0.4957, 0.1565],
          [0.4106, 0.3337, 0.1249,  ..., 0.3153, 0.5953, 0.7690],
          [0.2774, 0.6450, 0.8585,  ..., 0.4880, 0.6455, 0.7289],
          ...,
          [0.5964, 0.1655, 0.5616,  ..., 0.9649, 0.3921, 0.2171],
          [0.6823, 0.9518, 0.0218,  ..., 0.0734, 0.7105, 0.0489],
          [0.1449, 0.6195, 0.6422,  ..., 0.8546, 0.8082, 0.7061]],

         [[0.5813, 0.9426, 0.1350,  ..., 0.1620, 0.2444, 0.4773],
          [0.5899, 0.0229, 0.8148,  ..., 0.3824, 0.8823, 0.4939],
          [0.6159, 0.1237, 0.0712,  ..., 0.6144, 0.6846, 0.4361],
          ...,
          [0.7996, 0.0960, 0.5238,  ..., 0.3947, 0.4236, 0.6397],
          [0.7720, 0.9198, 0.2731,  ..., 0.3201, 0.8555, 0.2444],
          [0.1587, 0.8143, 0.1941,  ..., 0.1623, 0.5362, 0.6875]],

         [[0.5952, 0.1398, 0.4817,  ..., 0.8703, 0.9591, 0.3281],
          [0.3220, 0.6353, 0.6695,  ..., 0.5856, 0.3809, 0.5560],
          [0.0250, 0.5016, 0.0281,  ..., 0

In [3]:
a[0].shape

torch.Size([3, 28, 28])

In [4]:
a[0,0].shape

torch.Size([28, 28])

In [5]:
a[0,0,2,4] # 此代码等价于a[0][0][2][4]


tensor(0.9212)

In [10]:
a[0][0][2][4]

tensor(0.9212)

select first/last N

In [7]:
a.shape

torch.Size([4, 3, 28, 28])

In [8]:
a[:2].shape

torch.Size([2, 3, 28, 28])

In [9]:
a[:2,:1,:,:].shape

torch.Size([2, 1, 28, 28])

In [11]:
a[:2,1:,:,:].shape

torch.Size([2, 2, 28, 28])

In [12]:
a[:2,-1:,:,:].shape

torch.Size([2, 1, 28, 28])

select by steps

In [13]:
a[:,:,0:28:2,:].shape

torch.Size([4, 3, 14, 28])

In [14]:
a[:,:,::2,::2].shape

torch.Size([4, 3, 14, 14])

select by specific index

In [15]:
a.shape

torch.Size([4, 3, 28, 28])

In [19]:
# index_select函数

a = torch.rand(4,3,28,28)
a
a.shape
torch.index_select(a,0,torch.tensor([0,2])).shape
torch.index_select(a,1,torch.tensor([0,2])).shape


torch.Size([4, 2, 28, 28])

In [20]:
a.index_select(2,torch.arange(28)).shape

torch.Size([4, 3, 28, 28])

In [21]:
a.index_select(2,torch.arange(8)).shape

torch.Size([4, 3, 8, 28])

In [22]:
a.shape

torch.Size([4, 3, 28, 28])

In [23]:
a[...].shape

torch.Size([4, 3, 28, 28])

In [24]:
a[0,...].shape

torch.Size([3, 28, 28])

In [25]:
a[:,1,...].shape

torch.Size([4, 28, 28])

In [26]:
a[...,:2].shape

torch.Size([4, 3, 28, 2])

select by mask

In [32]:
# mask_select函数
# mask_select函数的作用是根据掩码的真值来选择元素
x = torch.randn(3,4)
x

tensor([[ 2.0016,  0.8680,  0.3676,  0.1874],
        [-1.0185,  0.8151,  0.6021, -0.2684],
        [ 0.4205,  0.1501,  0.2220, -1.5253]])

In [33]:
mask = x.ge(0.5)
mask

tensor([[ True,  True, False, False],
        [False,  True,  True, False],
        [False, False, False, False]])

In [34]:
torch.masked_select(x,mask)

tensor([2.0016, 0.8680, 0.8151, 0.6021])

In [35]:
torch.masked_select(x,mask).shape


torch.Size([4])

select by flatten index

In [36]:
src = torch.tensor([[4,3,5],[6,7,8]])

In [37]:
torch.take(src,torch.tensor([0,2,5]))

tensor([4, 5, 8])