Math operation

Add/minus/multiply/divide

Matmul

Pow

Sqrt/rsqrt

Round


In [2]:
import torch
a = torch.rand(3,4)
b = torch.rand(4)

a+b

tensor([[0.6387, 0.9271, 1.2127, 0.5023],
        [1.0630, 1.5922, 1.5384, 0.9233],
        [1.0136, 1.8327, 0.9145, 0.2764]])

In [3]:
torch.add(a,b)

tensor([[0.6387, 0.9271, 1.2127, 0.5023],
        [1.0630, 1.5922, 1.5384, 0.9233],
        [1.0136, 1.8327, 0.9145, 0.2764]])

In [4]:
torch.all(torch.eq(a-b,torch.sub(a,b)))

tensor(True)

In [5]:
torch.all(torch.eq(a*b,torch.mul(a,b)))

tensor(True)

In [6]:
torch.all(torch.eq(a/b,torch.div(a,b)))

tensor(True)

matmul

Torch.mm

Torch,matmul

@

In [13]:
a = torch.tensor([[3,3],[3,3]],dtype=torch.float32)

a

tensor([[3., 3.],
        [3., 3.]])

In [15]:
b = torch.ones(2,2)
b

tensor([[1., 1.],
        [1., 1.]])

In [16]:
torch.mm(a,b)

tensor([[6., 6.],
        [6., 6.]])

In [17]:
a@b

tensor([[6., 6.],
        [6., 6.]])

In [21]:
a = torch.rand(4,784)
x = torch.rand(4,784)
w = torch.rand(512,784)
(x@w.t()).shape

torch.Size([4, 512])

\> 2d tensor

In [22]:
a = torch.rand(4,3,28,64)
b = torch.rand(4,3,64,32)
torch.mm(a,b).shape

RuntimeError: self must be a matrix

In [23]:
torch.matmul(a,b).shape

torch.Size([4, 3, 28, 32])

In [24]:
b = torch.rand(4,1,64,32)

torch.matmul(a,b).shape


torch.Size([4, 3, 28, 32])

In [25]:
b = torch.rand(4,64,32)

torch.matmul(a,b).shape


RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

Power

In [26]:
a = torch.full([2,2],3)
a.pow(2)

tensor([[9, 9],
        [9, 9]])

In [27]:
a**2

tensor([[9, 9],
        [9, 9]])

In [28]:
aa = a**2
aa.sqrt()

tensor([[3., 3.],
        [3., 3.]])

In [29]:
aa.rsqrt()

tensor([[0.3333, 0.3333],
        [0.3333, 0.3333]])

In [30]:
aa**(0.5)

tensor([[3., 3.],
        [3., 3.]])

Exp log

In [31]:
a = torch.exp(torch.ones(2,2))
a

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [32]:
torch.log(a)

tensor([[1., 1.],
        [1., 1.]])

Approximation

.floor().ceil()

.round()

.trunc().frac()

In [37]:
a = torch.tensor(3.14)
a.floor(), a.ceil(),a.trunc(),a.frac()

(tensor(3.), tensor(4.), tensor(3.), tensor(0.1400))

In [36]:
a = torch.tensor(3.499)
a.round()

tensor(3.)

In [38]:
a = torch.tensor(3.5)

a.round()

tensor(4.)

clamp

gradient clipping

(min)

(min,max)


In [40]:
grad = torch.rand(2,3)*15

grad.max()

tensor(14.5099)

In [41]:
grad.median() 

tensor(3.0123)

In [42]:
grad.clamp(10) # 小于10的数变成10

tensor([[14.5099, 10.0000, 10.0000],
        [10.0000, 10.0000, 14.4580]])

In [43]:
grad.clamp(0,10) # 小于0的数变成0，大于10的数变成10


tensor([[10.0000,  0.6678,  7.9245],
        [ 1.8744,  3.0123, 10.0000]])