statistics

norm

mean sum

prod

max,min,argmin,argmax

kthvalue,topk




norm

vs normalize, eg batchnorm

matrix norm vs vector norm

In [7]:
import torch 
a = torch.full([8],1,dtype=torch.float32)

In [8]:
b = a.view(2,4)
c = a.view(2,2,2)

In [9]:
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
c

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [11]:
a.norm(1),b.norm(1),c.norm(1)

(tensor(8.), tensor(8.), tensor(8.))

In [12]:
a.norm(2),b.norm(2),c.norm(2)

(tensor(2.8284), tensor(2.8284), tensor(2.8284))

In [13]:
b.norm(1,dim=1)

tensor([4., 4.])

In [14]:
b.norm(2,dim=1)

tensor([2., 2.])

In [16]:
c.norm(1,dim=0)

tensor([[2., 2.],
        [2., 2.]])

In [17]:
c.norm(2,dim=0)

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])

mean,sum,min,max,prod

In [19]:
a = torch.arange(8).view(2,4).float()
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [20]:
a.sum()

tensor(28.)

In [21]:
a.argmax(),a.argmin()

(tensor(7), tensor(0))

In [23]:
a = a.view(1,2,4)
a

tensor([[[0., 1., 2., 3.],
         [4., 5., 6., 7.]]])

In [25]:
a.argmax(),a.argmin()

(tensor(7), tensor(0))

In [27]:
a = torch.rand(2,3,4)
a

tensor([[[0.9512, 0.3090, 0.5148, 0.5070],
         [0.2522, 0.1316, 0.4383, 0.1297],
         [0.6115, 0.5310, 0.1195, 0.5598]],

        [[0.6796, 0.7193, 0.3506, 0.3078],
         [0.8779, 0.7250, 0.5845, 0.3188],
         [0.7146, 0.2673, 0.8606, 0.2144]]])

In [28]:
a.argmax()

tensor(0)

In [29]:
a = torch.randn(4,10)

In [31]:
a[0]

tensor([-1.2832,  1.7420,  1.6221, -1.0511,  0.1135,  1.3099, -0.5698,  1.3034,
         1.0233, -0.8038])

In [32]:
a.argmax()

tensor(34)

In [33]:
a.argmax(dim=1)

tensor([1, 6, 8, 4])

dim,keepdim

In [34]:
a

tensor([[-1.2832,  1.7420,  1.6221, -1.0511,  0.1135,  1.3099, -0.5698,  1.3034,
          1.0233, -0.8038],
        [-2.5408, -0.1824, -1.4377,  0.4089, -1.6410,  0.2324,  0.8885, -0.6360,
         -0.7441,  0.7857],
        [ 0.2240, -1.1141,  0.9201, -0.2248,  0.5618,  0.3590, -0.2252, -1.8935,
          1.0956,  0.0990],
        [ 0.0831, -0.6781, -0.6037, -0.2705,  1.9398,  1.9357,  0.5420,  1.0705,
          0.4166, -0.2822]])

In [35]:
a.max(dim=1)

torch.return_types.max(
values=tensor([1.7420, 0.8885, 1.0956, 1.9398]),
indices=tensor([1, 6, 8, 4]))

In [36]:
a.argmax(dim=1)

tensor([1, 6, 8, 4])

In [37]:
a.max(dim = 1,keepdim=True)

torch.return_types.max(
values=tensor([[1.7420],
        [0.8885],
        [1.0956],
        [1.9398]]),
indices=tensor([[1],
        [6],
        [8],
        [4]]))

In [38]:
a.argmax(dim=1,keepdim=True)

tensor([[1],
        [6],
        [8],
        [4]])

Top-k or k-th

In [39]:
a.topk(3,dim=1)

torch.return_types.topk(
values=tensor([[1.7420, 1.6221, 1.3099],
        [0.8885, 0.7857, 0.4089],
        [1.0956, 0.9201, 0.5618],
        [1.9398, 1.9357, 1.0705]]),
indices=tensor([[1, 2, 5],
        [6, 9, 3],
        [8, 2, 4],
        [4, 5, 7]]))

In [40]:
a.topk(3,dim=1,largest=False)

torch.return_types.topk(
values=tensor([[-1.2832, -1.0511, -0.8038],
        [-2.5408, -1.6410, -1.4377],
        [-1.8935, -1.1141, -0.2252],
        [-0.6781, -0.6037, -0.2822]]),
indices=tensor([[0, 3, 9],
        [0, 4, 2],
        [7, 1, 6],
        [1, 2, 9]]))

In [41]:
a.kthvalue(8,dim=1)

torch.return_types.kthvalue(
values=tensor([1.3099, 0.4089, 0.5618, 1.0705]),
indices=tensor([5, 3, 4, 7]))

In [42]:
a.kthvalue(3)

torch.return_types.kthvalue(
values=tensor([-0.8038, -1.4377, -0.2252, -0.2822]),
indices=tensor([9, 2, 6, 9]))

In [43]:
a.kthvalue(3,dim=1)

torch.return_types.kthvalue(
values=tensor([-0.8038, -1.4377, -0.2252, -0.2822]),
indices=tensor([9, 2, 6, 9]))

compare

In [44]:
a > 0

tensor([[False,  True,  True, False,  True,  True, False,  True,  True, False],
        [False, False, False,  True, False,  True,  True, False, False,  True],
        [ True, False,  True, False,  True,  True, False, False,  True,  True],
        [ True, False, False, False,  True,  True,  True,  True,  True, False]])

In [45]:
torch.gt(a,0)

tensor([[False,  True,  True, False,  True,  True, False,  True,  True, False],
        [False, False, False,  True, False,  True,  True, False, False,  True],
        [ True, False,  True, False,  True,  True, False, False,  True,  True],
        [ True, False, False, False,  True,  True,  True,  True,  True, False]])

In [48]:
a!= 0

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [49]:
a = torch.ones(2,3)

In [50]:
b = torch.randn(2,3)

In [51]:
torch.eq(a,b)

tensor([[False, False, False],
        [False, False, False]])

In [52]:
torch.eq(a,a)

tensor([[True, True, True],
        [True, True, True]])