In [1]:
import torch

where

In [4]:
cond = torch.rand(2,2)
cond

tensor([[0.4365, 0.4911],
        [0.7771, 0.3985]])

In [6]:
a = torch.zeros(2,2)
a

tensor([[0., 0.],
        [0., 0.]])

In [9]:
b = torch.ones(2,2)
b

tensor([[1., 1.],
        [1., 1.]])

In [10]:
torch.where(cond > 0.5, a, b)

tensor([[1., 1.],
        [0., 1.]])

gather

retrieve label

In [11]:
prob = torch.randn(4, 10)


In [27]:
idx = prob.topk(dim=1, k=3)
idx

torch.return_types.topk(
values=tensor([[1.5250, 1.0778, 0.8881],
        [1.2365, 1.1666, 0.9027],
        [0.8165, 0.7975, 0.3690],
        [2.4735, 1.0031, 0.7325]]),
indices=tensor([[8, 7, 5],
        [2, 6, 3],
        [6, 9, 2],
        [8, 9, 0]]))

In [28]:
idx[1]

tensor([[8, 7, 5],
        [2, 6, 3],
        [6, 9, 2],
        [8, 9, 0]])

In [29]:
label = torch.arange(10) + 100
label   

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [34]:
torch.gather(label.expand(4, 10), dim=1, index=idx[1])

tensor([[108, 107, 105],
        [102, 106, 103],
        [106, 109, 102],
        [108, 109, 100]])